### PR TITLE
[netflix subs] restore support for batch downloads

### PR DESCRIPTION
**Pull request by aci2n**
I saw the batch download functionality was commented out (probably because something changed in the Netflix UI) and tried to restore it with a different approach. I tested with a couple series and it looks fine so far.
Thanks a lot for this script by the way.

Note: in Brave this requires the site to have the "automatic downloads" permission, I suppose other browsers will need the same.

### CODE REVIEW

**Comment by Tithen-Firion** [comment]
I considered that approach and decided not to use it. For each `.zip` file a `Blob` object is generated and then the URL created for that blob. From what I read those blobs and URLs live as long as the document does. You go to the next episode by changing the URL - and that's when the previous document "dies". I would have to check the behaviour of many different browsers to make sure the script works as intended.

In Chrome, same as in Brave, download is blocked until you allow automatic downloads - that's bad because I can't detect it and tell the user to do that. The script will keep grabbing subs from other episodes with no way to download them...

In Firefox it works only because this browser starts the download even before you click "OK" in the download prompt. But then again you get a lot of prompts. Not ideal.

That's why I want to stick to the **one click = one download** approach.

Some other minor issues in this PR that could potentially lead to unintended behaviour:
* clicking on the progress bar to stop the download doesn't work, should've used `if(!stop && nextEpisodeId)`
* I swear the seasons/episodes were out of order last time I checked, I'm going to sort them just in case
* race condition - in a very unlikely (but plausible) event `downloadAll` is called twice - from `processMetadata` and `processSubInfo`

When testing your PR it somehow opened a recap episode but I can't reproduce it again - and when that happened I got the "Couldn't find the subs. Wait until the player is loaded. If that doesn't help refresh the page." error. So I need to make some changes, batch downloading should wait for the title/subs before showing that error (I think 30 seconds is fine).

Another thing I don't necessarily like is storing just the next episode ID. Since the script already grabs IDs of all episodes it's possible to add 2 more buttons - "Download subs for this season" and "Download subs for all seasons". So I'm going to store all IDs that need to be downloaded. With that all 3 batch buttons could use the same logic with different list of IDs.

I like the idea of going to the main page not to spoil stuff but it's still the same blob issue from the first paragraph.

I'm leaving this PR open for now so other people can find it easily.

**Comment by aci2n** [comment]
Sounds reasonable, I didn't consider all those cases.
Only thing I'd point out is that I don't think there can be a race condition which would call `downloadAll()` twice since JS is single-threaded in the browser and there are no async callbacks in that section. The "loaded" flags could probably be replaced by something like `Object.keys(theOtherCache).length > 0` or something similar to check if everything's loaded.

**Comment by Tithen-Firion** [comment]
`processSubInfo` is async callback though. Anyway, I'll leave that part as it was. Nothing in `processMetadata` and just a check for `batch` in `processSubInfo`.

I'll add a 30 second timeout to `getXFromCache`. With fast internet there shouldn't be any problems. With slow one there shouldn't be any either because from what I've seen Netflix first loads the metadata and then the episode info. So `downloadAll` should run after both are loaded anyway.

2 more things I forgot to say. `unsafeWindow.location` is unnecessary, `window.location` works just fine. And while adding `subtitle-batch` to the URL should work fine - if the Netflix JS runs before the script and changes the URL (this happens sometimes) batch download will break. So I'm considering using `sessionStorage`.

Thank you for the PR though. Explaining this stuff helped me clarify the solution I have in mind. ;)

**Comment by aci2n** [comment]
Nice, looking forward to it 👍

**Comment by Tithen-Firion** [comment]
Try 4.1.0

**Pull request closed without merging**
